---
title: "Alpraz ALFF"
author: "Valerie Jill Sydnor"
output: html_document
---

```{r setup, include=FALSE}
library(ciftiTools)
library(catch22)
library(rgl)
ciftiTools.setOption('wb_path', '/Users/valeriesydnor/Software/workbench/')
rgl::setupKnitr()
library(zoo)
```


```{r}
participants <- read.csv("/cbica/projects/spatiotemp_dev_plasticity/Inhibition/Alpraz/sub_ses_passQC_finallist.csv", header = FALSE)
```

```{r}
xii.mask <- read_xifti("/cbica/projects/spatiotemp_dev_plasticity/Inhibition/Alpraz/catch22/group_cortex_mask.dscalar.nii")
```

Mask each subject's ALFF surface data

```{r}
mask_ALFF_data <- function(subid, sesid){
  
  #load in the ALFF map
  cifti.path = sprintf("/cbica/projects/spatiotemp_dev_plasticity/Inhibition/Alpraz/xcpabcd/task_regress/surface/xcp_abcd/%1$s/%2$s/func/%1$s_%2$s_task-emotionid_space-fsLR_den-91k_desc-alff_smooth_den-91k_bold.dtseries.nii", subid, sesid)
  xii <- read_xifti(cifti.path)
  
  #mask it
  ALFF.Lcortex.masked <- sweep(xii$data$cortex_left, MARGIN = 1, xii.mask$data$cortex_left, `*`)  
  ALFF.Rcortex.masked <- sweep(xii$data$cortex_right, MARGIN = 1, xii.mask$data$cortex_right, `*`)  
  
  xii.ALFF.masked <- as_xifti(cortexL = ALFF.Lcortex.masked, cortexR = ALFF.Rcortex.masked)
  dir.create(path = sprintf("/cbica/projects/spatiotemp_dev_plasticity/Inhibition/Alpraz/alff/%1$s/%2$s/", subid, sesid), recursive = TRUE)
  write_xifti(xii.ALFF.masked, file.path(sprintf("/cbica/projects/spatiotemp_dev_plasticity/Inhibition/Alpraz/alff/%1$s/%2$s/%1$s_%2$s_task-emotionid_space-fsLR_den-91k_desc-alff_smooth_masked_den-91k_bold.dscalar.nii", subid, sesid)))
  
  rm(xii)
}
```

```{r}
for(row in c(1:nrow(participants))){
  subid=participants[row,1]
  sesid=participants[row,2]
  mask_ALFF_data(subid, sesid)
}
```

Make a group average ALFF map

```{r}
for(row in c(1:nrow(participants))){
  subid=participants[row,1]
  sesid=participants[row,2]
  leftmatrix_name <- sprintf("Mleft%s", row)
  rightmatrix_name <- sprintf("Mright%s", row)
  cifti.path = sprintf("/cbica/projects/spatiotemp_dev_plasticity/Inhibition/Alpraz/alff/%1$s/%2$s/%1$s_%2$s_task-emotionid_space-fsLR_den-91k_desc-alff_smooth_masked_den-91k_bold.dscalar.nii", subid, sesid)
  xii <- read_xifti(cifti.path)
  leftmatrix_name <- assign(leftmatrix_name, xii$data$cortex_left)
  rightmatrix_name <- assign(rightmatrix_name, xii$data$cortex_right)
  rm(xii)
}
```

```{r}
matrix.list.left <- list(Mleft1, Mleft2, Mleft3, Mleft4, Mleft5, Mleft6, Mleft7, Mleft8, Mleft9, Mleft10,
                         Mleft11, Mleft12, Mleft13, Mleft14, Mleft15, Mleft16, Mleft17, Mleft18, Mleft19, Mleft20,
                         Mleft21, Mleft22, Mleft23, Mleft24, Mleft25, Mleft26, Mleft27, Mleft28, Mleft29, Mleft30,
                         Mleft31, Mleft32, Mleft33, Mleft34, Mleft35, Mleft36, Mleft37, Mleft38, Mleft39, Mleft40,
                         Mleft41, Mleft42, Mleft43, Mleft44, Mleft45, Mleft46, Mleft47, Mleft48, Mleft49, Mleft50,
                         Mleft51, Mleft52, Mleft53, Mleft54, Mleft55, Mleft56, Mleft57, Mleft58, Mleft59, Mleft60,
                         Mleft61, Mleft62, Mleft63, Mleft64, Mleft65, Mleft66, Mleft67, Mleft68, Mleft69, Mleft70,
                         Mleft71, Mleft72, Mleft73, Mleft74, Mleft75, Mleft76, Mleft77, Mleft78, Mleft79, Mleft80,
                         Mleft81, Mleft82, Mleft83, Mleft84)

leftcortex.group.ALFF <- Reduce("+", matrix.list.left)/length(matrix.list.left)
```

```{r}
matrix.list.right <- list(Mright1, Mright2, Mright3, Mright4, Mright5, Mright6, Mright7, Mright8, Mright9, Mright10,
                         Mright11, Mright12, Mright13, Mright14, Mright15, Mright16, Mright17, Mright18, Mright19, Mright20,
                         Mright21, Mright22, Mright23, Mright24, Mright25, Mright26, Mright27, Mright28, Mright29, Mright30,
                         Mright31, Mright32, Mright33, Mright34, Mright35, Mright36, Mright37, Mright38, Mright39, Mright40,
                         Mright41, Mright42, Mright43, Mright44, Mright45, Mright46, Mright47, Mright48, Mright49, Mright50,
                         Mright51, Mright52, Mright53, Mright54, Mright55, Mright56, Mright57, Mright58, Mright59, Mright60,
                         Mright61, Mright62, Mright63, Mright64, Mright65, Mright66, Mright67, Mright68, Mright69, Mright70,
                         Mright71, Mright72, Mright73, Mright74, Mright75, Mright76, Mright77, Mright78, Mright79, Mright80,
                         Mright81, Mright82, Mright83, Mright84)

rightcortex.group.ALFF <- Reduce("+", matrix.list.right)/length(matrix.list.right)
```

```{r}
xii.ALFF.average.map <- as_xifti(cortexL = leftcortex.group.ALFF, cortexR = rightcortex.group.ALFF)
xii.ALFF.average.map$meta$cifti$intent <- "3006"
write_xifti(xii.ALFF.average.map, file.path("/cbica/projects/spatiotemp_dev_plasticity/Inhibition/Alpraz/alff/ALFF_average_map.dscalar.nii"))
```

```{r}
xii.ALFF.average.map$data$cortex_left[xii.ALFF.average.map$data$cortex_left == 0 ] <- NA
xii.ALFF.average.map$data$cortex_right[xii.ALFF.average.map$data$cortex_right == 0 ] <- NA
surfL_fname <- read_surf("/Users/valeriesydnor/Software/workbench/workbench_files/Q1-Q6_R440.L.midthickness.32k_fs_LR.surf.gii")
surfR_fname <- read_surf("/Users/valeriesydnor/Software/workbench/workbench_files/Q1-Q6_R440.R.midthickness.32k_fs_LR.surf.gii")
xii.ALFF.average.map <- add_surf(xii.ALFF.average.map, surfL=surfL_fname, surfR=surfR_fname)
view_xifti_surface(xii.ALFF.average.map, colors=c("magma"), zlim=c(.2,1))
```

Prepare ALFF data for PCA

```{r}
ALFF.matrix <- matrix(NA, ncol=59412, nrow=nrow(participants))

for(row in c(1:nrow(participants))){
  subid=participants[row,1]
  sesid=participants[row,2]
  cifti.path = sprintf("/cbica/projects/spatiotemp_dev_plasticity/Inhibition/Alpraz/alff/%1$s/%2$s/%1$s_%2$s_task-emotionid_space-fsLR_den-91k_desc-alff_smooth_masked_den-91k_bold.dscalar.nii", subid, sesid)
  xii <- read_xifti(cifti.path)
  
  lh.data <- t(xii$data$cortex_left[,1])
  rh.data <- t(xii$data$cortex_right[,1])
  cortex.data <- cbind(lh.data, rh.data)
  ALFF.matrix[row,] <- cortex.data
  
  rm(lh.data)
  gc()
  rm(rh.data)
  gc()
  rm(cortex.data)
  gc()
  rm(xii)
  gc()
}

saveRDS(ALFF.matrix, file = "/cbica/projects/spatiotemp_dev_plasticity/Inhibition/Alpraz/alff/pca/ALFF.subxvertex.matrix.Rdata")
```

Run PCA on ALFF inputs
```{r}
inputmatrix <- readRDS("/cbica/projects/spatiotemp_dev_plasticity/Inhibition/Alpraz/alff/pca/ALFF.subxvertex.matrix.Rdata")
  
inputmatrix[inputmatrix == 0] <- NA #convert 0s to NAs
inputmatrix <- as.data.frame(inputmatrix) #convert matrix to df
inputmatrix.cleaned <- inputmatrix[, unlist(lapply(inputmatrix, function(x) !all(is.na(x))))] #remove all columns (vertices) with null data (all NAs)
inputmatrix.final <- na.approx(inputmatrix.cleaned, na.rm = F)
inputmatrix.final <- as.data.frame(inputmatrix.final) %>% dplyr::select(-V50027, -V49935, -V49995, -V50071, -V50072, -V50202, -V50203, -V50243, -V50244,  -V50283, -V50284, -V50323)

#PCA
ALFF.pca <- prcomp(inputmatrix.final, scale. = TRUE, center = TRUE) 
saveRDS(ALFF.pca, file = "/cbica/projects/spatiotemp_dev_plasticity/Inhibition/Alpraz/alff/pca/loadings/ALFF.pca.loadings.Rdata")
```

```{r}
#How much variance do the first ten components explain?
print(summary(ALFF.pca)$importance[2,1:10]*100)
  
#Scree plot #eblow room eblow room
pve <- 100*(ALFF.pca$sdev)^2/sum ((ALFF.pca$sdev)^2)

plot(pve, pch=16, 
     xlab="Principal Components",
     ylab="Prop. of variance explained")
```

```{r}  
#Save each subject's first 10 PCs to a csv
ALFF.pca.scores <- as.data.frame(ALFF.pca$x[,1:10]) #every subject's data (rows) for the first 10 PCs
ALFF.pca.scores$subid <- participants$V1 #match subids to scores
ALFF.pca.scores$sesid <- participants$V2 #match sesids to scores
write.csv(x= ALFF.pca.scores,
            file = ("/cbica/projects/spatiotemp_dev_plasticity/Inhibition/Alpraz/alff/pca/scores/ALFF.PCA.scores.csv"),
            quote = F, row.names = F)
```

```{r}
ALFF.pca.loadings.LH <- ALFF.pca$rotation[1:17737,1:10] #take loadings for the left cortex, and for the first 10 pcs
ALFF.pca.loadings.LH <- as.data.frame(ALFF.pca.loadings.LH)
loadings.left.cortex <- matrix(0, ncol=10, nrow=29696) #create an empty LH matrix
  for(row in c(1:nrow(ALFF.pca.loadings.LH))){
  vertexname <- row.names(ALFF.pca.loadings.LH[row,])
  vertexnumber <- as.numeric(sub('.', '', vertexname))
  loadings.left.cortex[vertexnumber,] <- unlist(ALFF.pca.loadings.LH[row,])
  }
xii.loadings.LH <- as_xifti(cortexL = loadings.left.cortex)
xii.loadings.LH$data$cortex_left[xii.loadings.LH$data$cortex_left == 0] <- NA #convert 0 vertices to NA
xii.loadings.LH <- add_surf(xii.loadings.LH, surfL=surfL_fname, surfR=surfR_fname)
```

```{r}
view_xifti_surface(xii.loadings.LH, idx=1, colors=c("RdBu"), hemisphere = c("left"), widget = TRUE)
```

```{r}
view_xifti_surface(xii.loadings.LH, idx=2, colors=c("RdBu"), hemisphere = c("left"), widget = TRUE)
```

```{r}
view_xifti_surface(xii.loadings.LH, idx=3, colors=c("RdBu"), hemisphere = c("left"), widget = TRUE)
```

Logistic Regression with ALFF PCs
```{r}
drugcode <- read.csv("/cbica/projects/spatiotemp_dev_plasticity/Inhibition/Alpraz/sub_ses_drugvplacebo.csv", header = TRUE)
```

```{r}
pca.scores <- read.csv("/cbica/projects/spatiotemp_dev_plasticity/Inhibition/Alpraz/alff/pca/scores/ALFF.PCA.scores.csv", header=T)
pca.scores <- merge(pca.scores, drugcode, by = "sesid")
  
logreg.ALFF.lm <- lm(pca.scores$drug ~ pca.scores$PC1 + pca.scores$PC2 + pca.scores$meanFD)
summary(logreg.ALFF.lm)

#logreg.ALFF <- glm(as.factor(pca.scores$drug) ~ pca.scores$PC1  + pca.scores$meanFD, family=binomial(logit)) 
#summary(logreg.ALFF)
```